### ISSUE TITLE
Installation issues: GitHub HTML probably changed

### ISSUE THREAD

**Issue by jplindstrom** [dxma/perl5-alien-libjq#1]
Trying to install `Alien::LibJQ`, but it fails with

```
"/home/xxx/perl5/perlbrew/perls/perl-5.32.0/bin/perl" -MAlien::Build::MM=cmd -e download
no matching files in listing at /home/xxx/.perlbrew/libs/perl-5.32.0@mybrew/lib/perl5/Alien/Build/Plugin/Core/Download.pm line 43.
```

Looks like the `alienfile ` https://github.com/dxma/perl5-alien-libjq/blob/master/alienfile#L19 contains 
```
version => qr/^jq-([0-9\.]+)\.tar\.gz$/o,
```

but that doesn't exist in the HTML on https://github.com/stedolan/jq/releases/ . I guess GitHub changed their HTML layout?

Could it work by just changing it to `qr/\bjq-([0-9\.]+)\.tar\.gz$/o,` ?

**Comment by dxma** [comment]
hi,

Thanks for trying my earlier proposal, indeed the github release download page has changed.
I am now cutting a  new release to stick with jq-1.6 for now. Like you said, it hasn't moved recently.
